### PR TITLE
add ffjson for faster json decoding

### PR DESCRIPTION
**Pull request by crosbymichael**
This helps reduce cpu usage when decoding json from runc.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by estesp** [comment]
this looks really valuable. Should there be some form of script or README addition that shows how they were generated in case it needs to be updated in the future and you aren't around? :)

**Comment by crosbymichael** [comment]
@estesp but i will last forever, I don't understand your concerns.

jk, good idea

**Comment by crosbymichael** [comment]
@estesp updated

**Comment by dqminh** [comment]
I think there's also https://github.com/json-iterator/go which doesnt require code-gen and is also really fast

**Comment by crosbymichael** [comment]
@dqminh nice.  i think that will be better because we can use it for spec marshal and unmarshal as well.

**Pull request closed without merging**
